require("config.options")
require("config.keymaps")
require("config.diagnostics")
require("config.autocmds")
require("config.lsp")

require("plugins.colorscheme")
require("plugins.mason")
require("plugins.formatter")
require("plugins.linter")
require("plugins.treesitter")
require("plugins.whichkey")
require("plugins.completion")
require("plugins.git")
require("plugins.statusline")
require("plugins.autopairs")
